# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  - name: dockerRegistryServiceConnection
    value: '92f28e96-f830-4c58-a8be-53591fd495f5'
  - name: tag
    value: '$(Build.BuildId)'
  - group: aks-vars

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: DockerAgents

    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(Build.SourcesDirectory)/azure-vote
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: AzureCLI@2
      displayName: 'Helm Package and Publish to ACR'
      inputs:
        azureSubscription: 'MyAzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd $(Build.SourcesDirectory)/azure-vote-front

          echo packaging helm files
          
          helm dependency update .

          helm package . -d ./charts
          
          ls -laR
          
          USER_NAME="helmtoken"
          PASSWORD=$(az acr token create -n $USER_NAME \
                            -r $(containerRegistry) \
                            --scope-map _repositories_admin \
                            --only-show-errors \
                            --query "credentials.passwords[0].value" -o tsv)
          
          
          helm registry login $(containerRegistry) \
              --username $USER_NAME \
              --password $PASSWORD
          
          helm push $(Build.SourcesDirectory)/azure-vote-front/charts/azure-vote-front-0.1.0.tgz  oci://$(containerRegistry)/helm
          
          helm push $(Build.SourcesDirectory)/azure-vote-front/charts/redis-17.3.17.tgz oci://$(containerRegistry)/helm

        addSpnToEnvironment: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/azure-vote-front/'
        ArtifactName: 'helmcharts'
        publishLocation: 'Container'